'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { AppShell } from '@/components/AppShell'
import { buildQuoteSuggestion, QuoteSuggestion } from '@/lib/quote-assistant'
import { supabase } from '@/lib/supabase'

type Dossier={id:string;dossier_name:string;purpose?:string|null;diagnostics?:string[]|string|null;property_address?:string|null;property_type?:string|null;property_size?:string|number|null;surface?:string|number|null;rooms?:string|number|null;dependencies?:string|null}
type Quote={id:string;quote_number:string;status:string;total_ht:number;total_vat:number;total_ttc:number;created_at:string;dossier_id:string}
type PropertyType='apartment'|'house'
type Measurement='none'|'boutin'|'attestation'
type FormState={dossier_id:string;propertyType:PropertyType;sizeKey:string;packCount:number;measurement:Measurement;assainissement:boolean;proximity:boolean;notes:string}

const apartmentPacks:Record<number,number[]>={2:[150,170,190,210,230],3:[180,200,220,240,260],4:[210,230,250,270,290],5:[240,260,280,300,320],6:[270,290,305,330,350],7:[290,310,325,360,380]}
const housePacks:Record<number,number[]>={2:[200,220,240,260,280],3:[240,260,280,300,320],4:[280,300,320,340,360],5:[320,340,360,380,400],6:[350,370,390,410,430]}
const boutinHouse=[70,90,110,130,150]
const apartmentLabels=['T1','T2','T3','T4','T5']
const houseLabels=['≤ 70 m²','71–100 m²','101–120 m²','121–150 m²','151–200 m²']
const euro=(n:number)=>n.toLocaleString('fr-FR',{style:'currency',currency:'EUR'})
const dateFr=(v:string)=>new Date(v).toLocaleDateString('fr-FR')
const quoteStatus=(s:string)=>({draft:'Brouillon',sent:'Envoyé',accepted:'Accepté'} as Record<string,string>)[s]||s

export default function DevisPage(){
 const router=useRouter();const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [dossiers,setDossiers]=useState<Dossier[]>([]);const [quotes,setQuotes]=useState<Quote[]>([])
 const [suggestion,setSuggestion]=useState<QuoteSuggestion|null>(null)
 const [form,setForm]=useState<FormState>({dossier_id:'',propertyType:'apartment',sizeKey:'0',packCount:2,measurement:'none',assainissement:false,proximity:false,notes:''})
 const load=async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session){router.replace('/login');return}const [d,q]=await Promise.all([supabase.from('dossiers').select('*').order('created_at',{ascending:false}),supabase.from('quotes').select('id,quote_number,status,total_ht,total_vat,total_ttc,created_at,dossier_id').order('created_at',{ascending:false}).limit(20)]);if(d.data){const requested=new URLSearchParams(window.location.search).get('dossier');setDossiers(d.data as Dossier[]);setForm(f=>({...f,dossier_id:f.dossier_id||d.data?.find(item=>item.id===requested)?.id||d.data?.[0]?.id||''}))}if(q.data)setQuotes(q.data as Quote[]);setLoading(false)}
 useEffect(()=>{void load()},[])
 const sizeIndex=Math.max(0,Math.min(4,Number(form.sizeKey)||0)),packTable=form.propertyType==='apartment'?apartmentPacks:housePacks,allowedPacks=form.propertyType==='apartment'?[2,3,4,5,6,7]:[2,3,4,5,6],effectivePack=allowedPacks.includes(form.packCount)?form.packCount:allowedPacks[0]
 const base=packTable[effectivePack]?.[sizeIndex]||0,measurement=form.propertyType==='house'&&form.measurement!=='none'?boutinHouse[sizeIndex]:0,assainissement=form.assainissement?(form.propertyType==='apartment'?100:160):0,proximity=form.proximity?-10:0,totalTtc=Math.max(0,base+measurement+assainissement+proximity),totalHt=Math.round(totalTtc/1.2*100)/100,vat=Math.round((totalTtc-totalHt)*100)/100
 const lines=useMemo(()=>{const out=[{label:`Pack ${effectivePack} diagnostics – ${form.propertyType==='apartment'?apartmentLabels[sizeIndex]:houseLabels[sizeIndex]}`,ttc:base}];if(form.propertyType==='house'&&form.measurement==='boutin')out.push({label:'Surface habitable – Loi Boutin',ttc:measurement});if(form.propertyType==='house'&&form.measurement==='attestation')out.push({label:'Attestation de mesurage',ttc:measurement});if(form.assainissement)out.push({label:'Contrôle de l’assainissement',ttc:assainissement});if(form.proximity)out.push({label:'Remise proximité Alfortville / Maisons-Alfort',ttc:-10});return out},[base,measurement,assainissement,form.measurement,form.assainissement,form.proximity,form.propertyType,sizeIndex,effectivePack])
 const analyzeDossier=()=>{setError('');const dossier=dossiers.find(item=>item.id===form.dossier_id);if(!dossier){setError('Choisis un dossier avant de lancer l’analyse.');return}setSuggestion(buildQuoteSuggestion(dossier))}
 const applySuggestion=()=>{if(!suggestion)return;const trace=[suggestion.diagnostics.length?`Missions détectées : ${suggestion.diagnostics.join(', ')}.`:'',...suggestion.warnings].filter(Boolean).join(' ');setForm(f=>({...f,propertyType:suggestion.propertyType,sizeKey:suggestion.sizeKey,packCount:suggestion.packCount,measurement:suggestion.propertyType==='house'&&suggestion.boutin?'boutin':'none',assainissement:suggestion.assainissement,proximity:suggestion.proximity,notes:[f.notes,trace].filter(Boolean).join('\n')}));setSuggestion(null)}
 const createQuoteNumber=async()=>{const d=new Date(),stamp=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`,prefix=`DEV-${stamp}-`;const {data}=await supabase.from('quotes').select('quote_number').like('quote_number',`${prefix}%`).order('quote_number',{ascending:false}).limit(1),last=data?.[0]?.quote_number||'',n=last?Number(last.slice(-3))+1:1;return `${prefix}${String(n).padStart(3,'0')}`}
 const save=async()=>{setError('');if(!form.dossier_id){setError('Choisis un dossier.');return}setSaving(true);const quoteNumber=await createQuoteNumber();const {data:q,error:qError}=await supabase.from('quotes').insert({dossier_id:form.dossier_id,quote_number:quoteNumber,status:'draft',total_ht:totalHt,total_vat:vat,total_ttc:totalTtc,property_type:form.propertyType,property_size:form.propertyType==='apartment'?apartmentLabels[sizeIndex]:houseLabels[sizeIndex],quote_kind:`pack_${effectivePack}`,notes:form.notes||null}).select('id').single();if(qError||!q){setError(qError?.message||'Impossible de créer le devis.');setSaving(false);return}const {error:lError}=await supabase.from('quote_lines').insert(lines.map((l,i)=>({quote_id:q.id,label:l.label,quantity:1,unit_ttc:l.ttc,total_ttc:l.ttc,sort_order:i})));if(lError){setError(lError.message);setSaving(false);return}setSaving(false);router.push(`/devis/${q.id}`)}
 if(loading)return <AppShell active="devis"><div className="loading">Chargement des devis…</div></AppShell>
 return <AppShell active="devis"><main className="page" style={{maxWidth:1280}}>
  <div className="hero-row"><div><div className="eyebrow">DEVIS</div><h1>Devis Express</h1><p>Prépare le montant, puis garde la validation finale avant envoi.</p></div></div>
  <div style={{display:'grid',gridTemplateColumns:'minmax(0,1.35fr) minmax(320px,.65fr)',gap:18,alignItems:'start'}}>
   <section className="card" style={{padding:22}}><h2 style={{marginTop:0,color:'#062b59'}}>Nouveau devis</h2>{error&&<div className="error">{error}</div>}<div className="edit-grid">
    <label className="edit-field wide"><span>Dossier</span><select value={form.dossier_id} onChange={e=>{setForm(f=>({...f,dossier_id:e.target.value}));setSuggestion(null)}}><option value="">Choisir un dossier…</option>{dossiers.map(d=><option key={d.id} value={d.id}>{d.dossier_name}</option>)}</select></label>
    <div className="wide" style={{display:'flex',alignItems:'center',gap:10,flexWrap:'wrap',padding:'12px 14px',border:'1px solid #cbddea',borderRadius:12,background:'#f5f9fd'}}><button type="button" className="ghost-btn" onClick={analyzeDossier}>✦ Générer une proposition</button><span style={{fontSize:13,color:'#52657a'}}>ARIA analyse le dossier, mais ne crée ni n’envoie rien sans ta validation.</span></div>
    {suggestion&&<div className="wide" style={{padding:16,border:'1px solid #a9d4bf',borderRadius:12,background:'#f2fbf6'}}><div className="eyebrow">PROPOSITION ARIA</div><h3 style={{margin:'4px 0 8px',color:'#062b59'}}>{suggestion.propertyType==='house'?'Maison':'Appartement'} · Pack {suggestion.packCount} diagnostics</h3>{suggestion.reasons.length>0&&<ul style={{margin:'0 0 10px',paddingLeft:20,color:'#315a48'}}>{suggestion.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>}{suggestion.warnings.length>0&&<div style={{padding:10,borderRadius:9,background:'#fff8e6',color:'#7a5612'}}><b>À vérifier avant validation</b><ul style={{margin:'6px 0 0',paddingLeft:20}}>{suggestion.warnings.map(warning=><li key={warning}>{warning}</li>)}</ul></div>}<div style={{display:'flex',gap:8,justifyContent:'flex-end',marginTop:12}}><button type="button" className="ghost-btn" onClick={()=>setSuggestion(null)}>Ignorer</button><button type="button" className="action-btn primary-action" onClick={applySuggestion}>Appliquer au brouillon</button></div></div>}
    <label className="edit-field"><span>Type de bien</span><select value={form.propertyType} onChange={e=>setForm(f=>({...f,propertyType:e.target.value as PropertyType,packCount:2,sizeKey:'0',measurement:'none'}))}><option value="apartment">Appartement</option><option value="house">Maison</option></select></label>
    <label className="edit-field"><span>{form.propertyType==='apartment'?'Type':'Surface'}</span><select value={form.sizeKey} onChange={e=>setForm(f=>({...f,sizeKey:e.target.value}))}>{(form.propertyType==='apartment'?apartmentLabels:houseLabels).map((x,i)=><option value={i} key={x}>{x}</option>)}</select></label>
    <label className="edit-field"><span>Nombre de diagnostics</span><select value={effectivePack} onChange={e=>setForm(f=>({...f,packCount:Number(e.target.value)}))}>{allowedPacks.map(n=><option key={n} value={n}>{n} diagnostics</option>)}</select></label><div/>
    {form.propertyType==='house'&&<label className="edit-field"><span>Mesurage facturé en option</span><select value={form.measurement} onChange={e=>setForm(f=>({...f,measurement:e.target.value as Measurement}))}><option value="none">Aucun</option><option value="boutin">Surface habitable – Loi Boutin</option><option value="attestation">Attestation de mesurage</option></select></label>}<label className="check-field"><input type="checkbox" checked={form.assainissement} onChange={e=>setForm(f=>({...f,assainissement:e.target.checked}))}/><span>Assainissement</span></label><label className="check-field"><input type="checkbox" checked={form.proximity} onChange={e=>setForm(f=>({...f,proximity:e.target.checked}))}/><span>Remise proximité -10 €</span></label>
    <label className="edit-field wide"><span>Notes internes</span><textarea rows={3} value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))} placeholder="Remise commerciale, précision dossier, information à vérifier…"/></label>
   </div></section>
   <aside className="card" style={{padding:22,position:'sticky',top:18}}><div className="eyebrow">APERÇU</div><h2 style={{margin:'4px 0 14px',color:'#062b59'}}>Montant du devis</h2><div style={{display:'grid',gap:9}}>{lines.map((l,i)=><div key={i} style={{display:'flex',justifyContent:'space-between',gap:12,borderBottom:'1px solid #edf2f7',paddingBottom:8}}><span>{l.label}</span><b>{euro(l.ttc)}</b></div>)}</div><div style={{marginTop:16,paddingTop:14,borderTop:'2px solid #dce6f0'}}><div style={{display:'flex',justifyContent:'space-between'}}><span>HT</span><b>{euro(totalHt)}</b></div><div style={{display:'flex',justifyContent:'space-between',marginTop:6}}><span>TVA 20 %</span><b>{euro(vat)}</b></div><div style={{display:'flex',justifyContent:'space-between',marginTop:10,fontSize:24,color:'#062b59'}}><strong>TTC</strong><strong>{euro(totalTtc)}</strong></div></div><button className="action-btn primary-action" style={{width:'100%',marginTop:18}} disabled={saving} onClick={save}>{saving?'Création…':'Créer le brouillon'}</button><p style={{fontSize:12,color:'#6f7d90',marginBottom:0}}>Le devis reste en brouillon : aucune transmission automatique.</p></aside>
  </div>
  <section className="section"><div className="section-title"><h2>Derniers devis</h2></div><div className="card table-card"><div className="table-head"><div>N° devis</div><div>Statut</div><div>TTC</div><div>Date</div></div>{quotes.length===0?<div className="table-row"><div>Aucun devis.</div></div>:quotes.map(q=><Link href={`/devis/${q.id}`} className="table-row" key={q.id}><div><b>{q.quote_number}</b></div><div><span className="status">{quoteStatus(q.status)}</span></div><div>{euro(Number(q.total_ttc||0))}</div><div>{dateFr(q.created_at)}</div></Link>)}</div></section>
 </main></AppShell>
}
